#! /usr/bin/env bash
# set -e

chmod +x /usr/sbin/ece-install
cat <<EOF
Thank you for installing ece-install. This is currently un-supported
software as it's undergoing heavy development. Be sure to check out
known issues at
https://github.com/escenic/ece-scripts/blob/master/known-issues.org and
report any issues to https://github.com/escenic/ece-scripts/issues

Have fun!

-Escenic
EOF

exit 0
