#! /usr/bin/env bash

# cron script to remove old cache files. These are the images that ECE
# generates whenever someone requests an image version (often refereed
# to as ALTERNATE int the URL & content-type).

dir=/var/cache/escenic/engine/binary

if [ -d $dir  ] ; then
  nice find $dir -type f -daystart -atime +15 -delete
  nice find $dir -type d -empty -delete 
fi
