#! /usr/bin/env bash

#          version: $Revision: #1 $ $Date: 2011/02/18 $
#           author: torstein@escenic.com
#   last update by: $Author: shud $

### BEGIN INIT INFO
# Provides:          ece
# Required-Start:    $remote_fs $network $syslog
# Required-Stop:     $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Escenic Content Engine
### END INIT INFO

#################################################################
# Usage:
# * copy this script to /etc/init.d/ece
# 
# * copy its configuration file to /etc/default/ece
#
# * make sure it's executable, chmod +x /etc/init.d/ece
#
# * add it to the desired runlevels, e.g. on Debian based systems this
#  would be: update-rc.d ece defaults
#######################################################################

#######################################################################
# Default values
#######################################################################
dir_list="
/var/log/escenic
/var/run/escenic
/var/cache/escenic
"

ece_script=/usr/bin/ece

# the values above may be overidden a file named the same as this
# init.d script, located in:
conf_file_location_list="
/etc/default
/tmp
"

function read_conf_file()
{
    for el in $conf_file_location_list; do
        if [ -r $el/`basename $0` ]; then
            source $el/`basename $0`
            found_conf=1
            break
        fi
    done

    if [ -z $found_conf ]; then
        echo "Couldn't find configuration for $0, exiting :-("
        exit 1
    fi
}

function ensure_dirs_are_ok()
{
    for el in $dir_list; do
        if [ ! -d $el ]; then
            mkdir -p $el
        fi
        chown -R $ece_unix_user:$ece_unix_group $el
    done
}

function ensure_ece_script_is_ok()
{
    if [ ! -r $ece_script ]; then
        echo "Couldn't read $ece_script"
        exit 1
    elif [ ! -x $ece_script ]; then
        echo "$ece_script needs to be executable (do: chmod +x $ece_script)"
        exit 1
    fi
    
}

function execute_command()
{
    if [ $enable_rmi_hub = "true" ]; then
        $ece_script -t rmi-hub $1
    fi
    
    for el in $engine_instance_list; do
        $ece_script -t engine -i $el $1
    done
    
    for el in $search_instance_list; do
        $ece_script -t search -i $el $1
    done
}

if [ $1 ]; then
    read_conf_file
    ensure_ece_script_is_ok
    ensure_dirs_are_ok
    execute_command $1
else
    echo "Usage: `basename $0` <start|stop|restart|status>"
fi
