
** Changing the Master DB
At install time, <%= my-db-master %> was the master DB and
<%= my-db-slave %> was the slave.

If you for some reason need to change the master to the slave, for
instance if you need to take down the server for maintenance, you must
do following steps described in this section.

*** Prepare <%= my-db-slave %> to become the new master
#+BEGIN_SRC text
$ ssh root@<%= my-db-slave %> 
# mysql <%= my-db %> 
#+END_SRC

You must then stop the IO thread of the slave:
#+BEGIN_SRC text
mysql> stop slave io_thread;
#+END_SRC

Next, you must wait for <%= my-db-slave %> to chew through everything
that <%= my-db-master %> has sent it. This information is stored in
<%= my-db-slave %>'s process list. To see how it's doing, do:
#+BEGIN_SRC text
mysql> show processlist;
#+END_SRC

What you're looking for, is for the slave to say: ~Slave has read all
relay log~. When ~show processlist~ says that, <%= my-db-slave %> is
ready to become master. 

If there's no mention of the relay at all, it could mean that
<%= my-db-slave %> has been replicating <%= my-db-master %> at all, or
that it's slave status have been turned off some while ago. As the
administrator, you must be the judge of that.

*** Promote <%= my-db-slave %> to master
Still in <%= my-db-slave %>'s mysql shell, do:
#+BEGIN_SRC text
mysql> stop slave;
mysql> reset master;
#+END_SRC

*** Make sure the replication user is available on <%= my-db-slave %>
This is the user the slave uses to replicate the master. Since
<%= my-db-slave %> hasn't done any replication before, you might want
to ensure that the replication user is there. The user and password
of the replication user is typically different than that of the user
ECE uses to access the DB.  

#+BEGIN_SRC text
grant replication slave on *.* 
  to 'replicationuser'@'%' 
  identified by 'replicationpassword';
flush privileges;
#+END_SRC

*** Set <%= my-db-master %> as slave of <%= my-db-slave %>
The steps are as follows: get the binary log position from
<%= my-db-slave %> and
set <%= my-db-master %> to be slave of <%= my-db-slave %>.

First, get the binary log & position from <%= my-db-slave %>:
#+BEGIN_SRC text
$ ssh root@<%= my-db-slave %>
# mysql <%= my-db %>
mysql> show master status;
#+END_SRC

The log file and the position are pretty much all that's outputted
from the mysql command above, so there shouldn't be anything to
confuse you.

Next, log on to <%= my-db-master %> and make it be a slave of
<%= my-db-slave %>:
#+BEGIN_SRC sql
reset master;
slave stop;

change master to
  master_host='<%= my-db-slave %>',
  master_user='replicationuser',
  master_password='replicationpassword',
  master_log_file='<%= my-db-slave %>-bin-file',
  master_log_pos=<position>
;

slave start;
#+END_SRC



