* Deployment
** Deploying a new EAR file
In the examples here, we have a build server on builder.example.com
where we build EARs for the the tomato website.

*** Deploying a new EAR file for an ECE instance
#+BEGIN_SRC sh
torstein@control:~$ sudo ssh escenic@pres1 ece -i engine1 --uri http://builder.example.com/tomato/releases/tomato-trunk-rev4121-2012-07-05_1524.ear  deploy
[ece#engine-engine1] Deploying http://builder.example.com/tomato/releases/tomato-trunk-rev4121-2012-07-05_1524.ear on engine1 ...
[ece#engine-engine1] Deploying /var/cache/escenic/tomato-trunk-rev4121-2012-07-05_1524.ear on tomcat ...
[ece#engine-engine1] Deployment white list active, only deploying: eb escenic-admin indexer-webservice
[ece#engine-engine1] Deployment state file updated: /var/lib/escenic/engine1.state
#+END_SRC

We can now restart the ECE:

#+BEGIN_SRC sh
torstein@control$ sudo ssh root@pres1 /etc/init.d/ece restart 
[ece#engine-engine1] Stopping the engine1 instance of engine on pres1 ...
[ece#engine-engine1] Starting the engine1 instance of engine on pres1 ...
[ece#search-search1] Stopping the search1 instance of search on pres1 ...
[ece#search-search1] Starting the search1 instance of search on pres1 ...
#+END_SRC

To confirm see that the ECE instance came up again, do:

#+BEGIN_SRC sh
torstein@control:~$ sudo ssh root@pres1 /etc/init.d/ece status
[ece#engine-engine1] UP 0d 0h 11m 45s
[ece#search-search1] UP 0d 0h 11m 42s
#+END_SRC

*** Deploying a new EAR file for a search instance
The search instance is special in that you have to specify the type
parameter. Apart from this, the command is identical. You'll see that
the search instance has a different deployment white list than that of
the ECE instance above.

#+BEGIN_SRC sh
torstein@control:~$ sudo ssh escenic@pres1 ece -i search1 -t search --uri http://builder.example.com/tomato/releases/tomato-trunk-rev4121-2012-07-05_1524.ear deploy
[ece#search-search1] Deploying http://builder.example.com/tomato/releases/tomato-trunk-rev4121-2012-07-05_1524.ear on search1 ...
[ece#search-search1] Deploying /var/cache/escenic/tomato-trunk-rev4121-2012-07-05_1524.ear on tomcat ...
[ece#search-search1] Deployment white list active, only deploying: escenic-admin solr indexer-webapp
[ece#search-search1] Deployment state file updated: /var/lib/escenic/search1.state  
#+END_SRC

** Updating Publication Resources
This document describes how you update publication resources. Here, we
use content-type as an example.

The content type publication resource is special because it's merged
by WF and you thus must take it from the EAR the build server built
for you. Other publication resources could be taken directly from the
SCM, but for consistency, you can just follow the guide below for
these as well (layout, layout-group, menu, community/security and so
on).

*** Extract the publication resources.
Make sure you have already done the deployment in the pres1 server

*** Login to one of the presentation servers
#+BEGIN_SRC sh
control$ sudo ssh root@pres1  
#+END_SRC

*** Change to the escenic user
#+BEGIN_SRC sh
pres1# su - escenic
#+END_SRC

*** Download current content-type
#+BEGIN_SRC sh
pres1$ wget -O ~/backup/content-type-$(date --iso)-before-deployment \
       http://localhost:8080/escenic-admin/publication-resources/mypub/escenic/content-type
#+END_SRC

*** Locate the new content-type definition
Go to the new new content-type from your latest deployment 

#+BEGIN_SRC sh
pres1$ cd /opt/tomcat-engine1/webapps/eb/META-INF/escenic/publication-resources/escenic/
#+END_SRC

*** Confirm the changes with diff
#+BEGIN_SRC sh
pres$ diff -w ~/backup/content-type-$(date --iso)-before-deployment content-type  
#+END_SRC


*** Now upload the new content-type to ECE
The command below assumes that there is a file called the same as the
publication resource in the current directory. Since we changed into
that directory in step 5), we can therefore now do:

#+BEGIN_SRC sh
pres1$ ece -i engine1 -p mypub -r content-type update
#+END_SRC


*** Download the resource again to check if its in place
#+BEGIN_SRC sh
pres1$ wget -O ~/backup/content-type-$(date --iso)-after-deployment \
               http://localhost:8080/escenic-admin/publication-resources/mypub/escenic/content-type
#+END_SRC


*** Do check with diff again
#+BEGIN_SRC sh
pres$ diff -w ~/backup/content-type-$(date --iso)-before-deployment \
              ~/backup/content-type-$(date --iso)-after-deployment
#+END_SRC


