* Deployment
** Building a new EAR file
Log on to the build server as the user for the given habitat and run
the build script:

#+BEGIN_SRC sh
$ ssh <%= trail_builder_user %>@<%= trail_builder_host %>
$ ./build.sh release
#+END_SRC

Once the build is done, the URI of the finished EAR file is printed in
the shell. This is the URI you use for the 'ece deploy' command below.

** Deploying a new EAR file
In the examples here, we have a build server on <%= trail_builder_host %>
where we build EARs for the the <%= trail_builder_user %> website.

** Make sure you can roll back
Before deploying a new EAR, take note of the previously deployed EAR
so that you can easily roll back:

#+BEGIN_SRC sh
$ sudo ssh escenic@<%= trail_presentation_host %> ece -i engine1 info
[ece#engine-engine1] Deployment state:
[ece#engine-engine1] |-> Version: <%= trail_builder_user %>-trunk-rev4331-<%= trail_today_date %>_1225
[ece#engine-engine1] |-> EAR used: http://<%= trail_builder_host %>/<%= trail_builder_user %>/releases/<%= trail_builder_user %>-trunk-rev4331-<%= trail_today_date %>_1225.ear
[ece#engine-engine1] |-> MD5 sum: 58638b16efc7f4cebd8d0acb4eecfb40
#+END_SRC

If anything goes wrong in [[Deploying a new EAR file for an ECE
instance]], you can just repeat the deployment steps with the URL of the
previous EAR.

*** Deploying a new EAR file for an ECE instance
All the commands in this section is written to be executed on
<%= trail_control_host %> (but you could of course also first log on to each
of the servers and run the commands locally there).

#+BEGIN_SRC sh
$ sudo ssh escenic@<%= trail_presentation_host %> ece -i engine1 --uri http://<%= trail_builder_host %>/<%= trail_builder_user %>/releases/<%= trail_builder_user %>-trunk-rev4121-<%= trail_today_date %>_1524.ear deploy
[ece#engine-engine1] Deploying http://<%= trail_builder_host %>/<%= trail_builder_user %>/releases/<%= trail_builder_user %>-trunk-rev4121-<%= trail_today_date %>_1524.ear on engine1 ...
[ece#engine-engine1] Deploying /var/cache/escenic/<%= trail_builder_user %>-trunk-rev4121-<%= trail_today_date %>_1524.ear on tomcat ...
[ece#engine-engine1] Deployment white list active, only deploying: <%= trail_webapp_name %> escenic-admin indexer-webservice
[ece#engine-engine1] Deployment state file updated: /var/lib/escenic/engine1.state
#+END_SRC

We can now restart the ECE:

#+BEGIN_SRC sh
$ sudo ssh root@<%= trail_presentation_host %> /etc/init.d/ece restart 
[ece#engine-engine1] Stopping the engine1 instance of engine on <%= trail_presentation_host %>...
[ece#engine-engine1] Starting the engine1 instance of engine on <%= trail_presentation_host %>...
[ece#search-search1] Stopping the search1 instance of search on <%= trail_presentation_host %>...
[ece#search-search1] Starting the search1 instance of search on <%= trail_presentation_host %>...
#+END_SRC

To confirm see that the ECE instance came up again, do:

#+BEGIN_SRC sh
$ sudo ssh root@<%= trail_presentation_host %> /etc/init.d/ece status
[ece#engine-engine1] UP 0d 0h 11m 45s
[ece#search-search1] UP 0d 0h 11m 42s
#+END_SRC

*** Deploying a new EAR file for a search instance
The search instance is special in that you have to specify the type
parameter. Apart from this, the command is identical. You'll see that
the search instance has a different deployment white list than that of
the ECE instance above.

#+BEGIN_SRC sh
torstein@control:~$ sudo ssh escenic@<%= trail_presentation_host %> ece
-i search1 -t search --uri http://<%= trail_builder_host %>/<%= trail_builder_user %>/releases/<%= trail_builder_user %>-trunk-rev4121-<%= trail_today_date %>_1524.ear deploy
[ece#search-search1] Deploying http://<%= trail_builder_host %>/<%= trail_builder_user %>/releases/<%= trail_builder_user %>-trunk-rev4121-<%= trail_today_date %>_1524.ear on search1 ...
[ece#search-search1] Deploying /var/cache/escenic/<%= trail_builder_user %>-trunk-rev4121-<%= trail_today_date %>_1524.ear on tomcat ...
[ece#search-search1] Deployment white list active, only deploying: escenic-admin solr indexer-webapp
[ece#search-search1] Deployment state file updated: /var/lib/escenic/search1.state  
#+END_SRC


** Updating Publication Resources
This document describes how you update publication resources. Here, we
use content-type as an example.

The content type publication resource is special because it's merged
by WF and you thus must take it from the EAR the build server built
for you. Other publication resources could be taken directly from the
SCM, but for consistency, you can just follow the guide below for
these as well (layout, layout-group, menu, community/security and so
on).

First, make sure you have already done the deployment on the
<%= trail_presentation_host %> server. Login to one of the presentation
servers. From <%= trail_control_host %>, do:
#+BEGIN_SRC sh
$ sudo ssh root@<%= trail_presentation_host %>
#+END_SRC

Then, change to the user running the ECE user
#+BEGIN_SRC sh
# su - escenic
#+END_SRC

After this, download current content-type so that we can keep a backup
of it.
#+BEGIN_SRC sh
$ mkdir ~/backup
$ wget -O ~/backup/content-type-$(date --iso)-before-deployment \
       http://localhost:8080/escenic-admin/publication-resources/<%= trail_publication_name %>/escenic/content-type
#+END_SRC

The next step is to locate the new content-type definition.  Go to the
new new content-type from your latest deployment

#+BEGIN_SRC sh
$ cd /opt/tomcat-engine1/webapps/<%= trail_webapp_name %>/META-INF/escenic/publication-resources/escenic/
#+END_SRC

Then, confirm the changes using diff:
#+BEGIN_SRC sh
$ diff -w ~/backup/content-type-$(date --iso)-before-deployment content-type  
#+END_SRC

Now, upload the new content-type to ECE.  The command below assumes
that there is a file called the same as the publication resource in
the current directory. 
#+BEGIN_SRC sh
$ ece -i engine1 -p <%= trail_publication_name %> -r content-type update
#+END_SRC

To confirm our changes, we now download the resource again to check if
all the changes are the way we want them:
#+BEGIN_SRC sh
$ wget -O ~/backup/content-type-$(date --iso)-after-deployment \
       http://localhost:8080/escenic-admin/publication-resources/<%= trail_publication_name %>/escenic/content-type
#+END_SRC

Finally, run diff again to see that the changes are correct:
#+BEGIN_SRC sh
$ diff -w ~/backup/content-type-$(date --iso)-before-deployment \
          ~/backup/content-type-$(date --iso)-after-deployment
#+END_SRC


