* Host naming conventions
This document assumes that you know how the global DNS system works.

Using hostnames to reach a service is preferred over using IP addresses directly because it gives us more routing flexibility. We can for instance change the IP address of a service without changing the client configuration.

We have a standard for naming hosts and the following text describes it.

** Machine roles

The follwing machine roles are common in VOSA clusters:

*** General
- Control :: (control) Ssh entrypoint operators
- Monitoring :: (mon) Presenting operational performance trends and sending out events when performance or capacity limits are exceded.

*** VME Online
- Controller :: (vmeoc) VME Admin web interface (Diactus), All automatic workflows of VME are initiated and monitored from here. Usually a VMEO control server can perform all roles in a VMEO service but delegates to other VMEO machines in order to scale for required transcoding capacity and delivery capacity.
- Delivery :: (vmeod*) Presenting video's to visitors either by streaming protocols or file transfer protocols.
- Transcoder :: (vmeot*) Transcoding video's from one format to another, either live or as a batch process. 

*** Escenic
- Escenic Presentation :: (pres*) Generating webpages by merging content from a database with html from JSP files.
- Escenic Editorial :: (edit*) Content Studio webservice, Imports
- Escenic Analysis :: (analysis) Counting pageimpressions for use by the webpages to present lists that depend on performance of specific content items.

** Virtual roles and IP addresses
We use virtual roles for internal services. Internal services are often a single point of failure so we must distribute the capability to perform internal services over multiple machines. Many machines should have the ability to perform any vrtual role but only one machine should actually play the role at any time.

When a machine assumes a role it often claims the corresponding [[http://en.wikipedia.org/wiki/Virtual_IP_address][virtual IP address]] (VIP). A VIP can sometimes be claimed automatically if a [[http://en.wikipedia.org/wiki/Heartbeat_(program)][Linux-HA setup]] is installed.

*** General

- Control :: (control) The control service currently in production
- Monitoring :: (mon) The monitoring service currently in production

*** VME-online

- Controller :: The server that happens to run the database and the JBOSS server containing the Diactus Web Application.

*** Escenic

- Analysis :: (analysis) the analysis webservices that are currently in production
- Editorial :: (edit) Content Studio webservice and Indexer Webservice that are currently in production
- Import jobs :: (import) All periodic downloads of external content currently going on.
- NFS master :: (nfs-master) The filesharing server that is curently in production.
- NFS slave :: (nfs-slave) The backup filesharing server that is curently in production and should represent the exact same content as the master with a slight.
- Presentation :: (pres*) The presentation hosts currently configured on the loadbalancer

** VOSA standard network naming
We use a standard naming scheme for all machines and virtual roles that we control.

<machine role>.<network name>.<customercode>.cust.vizrtsaas.com
<virtual role>.<customercode>.cust.vizrtsaas.com

** <%= trail_customer_shortname %> Network naming

| <%= trail_customer_shortname %> customer network  | <%= trail_customer_acronym %>                                                            |
| <%= trail_customer_shortname %> remote virtual roles     | <vrtual role><%= trail_customer_remote_datacentre %>.<%= trail_customer_acronym %>.cust.vizrtsaas.com |
| <%= trail_customer_shortname %> remote datacentre assets | <machine role><%= trail_customer_remote_datacentre %>.<%= trail_customer_acronym %>.cust.vizrtsaas.com |
| <%= trail_customer_shortname %> office network assets | <machine role><%= trail_customer_office_network %>.<%= trail_customer_acronym %>.cust.vizrtsaas.com |


