* Escenic Import Configuration Archive

An Escenic Import Configuration Archive (EICA) is a collection of files packaged in an archive that can import data into Escenic Engine. It can be deployed to any machine that has Escenic Engine running on it that was installed by ece-install.

** EICAs have the following features
- An execution plan :: You can include cron configuration to specify when and how often the import runs.
- A transformation plan :: You can specify the transformations that will be applied to the incoming data before it is imported to Escenic Content Engine.
- Standard locations :: A standard set of file locations to read from and write to.
- Standard monitoring :: Standard monitoring is available to ensure that performance can be analysed and operators can be  signalled about failures.
An Import Configuration Archive can be depoloyed to an Escenic Engine machine by adhering to the standards discribed in the rest of this document.

** Conventions
All file and directory names are to be lower cased with hyphens
between sub words, e.g. =my-import-configuration= and
=01-convert-from-atom-to-escenic-xml.xsl=.

All EICA's delivered to the VOSA operators are =zip=
archives with a strict structure, as defined in [[Specifying an EICA]]

** Specifying an EICA
When creating a new EICA for your project, the following directory
structure is required:

#+BEGIN_SRC text
<publication>/<import name>
<publication>/<import name>/transformers/<number>-<transformer task>.xsl
<publication>/<import name>/cron.hourly/<cron job script>
<publication>/<import name>/cron.every.<number>.minutes/<cron job script>
#+END_SRC

- publication name :: the name of the publication for which the import
     job(s) are defined. You can have more than one publication in
     each =zip= archive.
- import job name :: lowercase with hyphens between words (if more
     than one)
- transformers :: directory with files prefixed with =<number>-=, indicating
                  the order of transformation to apply to your import job. If
                  this is a =xsl= file, the escenic importer will run
                  =xsltproc= on the file, whereas =.sh= files will be
                  run in a =bash= wrapper.

                  Each of the transformers will be called with one
                  argument, namely the input XML data. Each
                  transformer is responsible to write changes back to
                  the file.
- cron.hourly :: scripts to be run every our. These will be put in
                 =/etc/cron.hourly= on the import server. Be sure to
                 set the execute bit on the file and note that as with
                 all cron jobs, the file cannot have a file suffix.
- cron.every.<number>.minutes :: scripts to run every =<number>= minutes.

We're calling the import configuration =moo= since we're
setting up an import feed from our imaginary content provider, "Moo
Cool Videos" and our publication is the ubiquitous =mypub=.

#+BEGIN_SRC text
$ unzip -t my-great-import-archive.zip.zip
mypub/moo/transformers/01-fix-encoding.sh
mypub/moo/transformers/02-convert-all-cows-to-ducks.xsl
mypub/moo/transformers/02-convert-duck-to-escenic-xml.xsl
mypub/moo/cron.hourly/get-files-from-moo-ftp
mypub/moo/cron.every.10.minutes/ask-for-public-ip
otherpub/foo/transformers/01-convert-from-foo-to-escenic-xml.xsl
#+END_SRC

As you can guess from the file names, the
=02-convert-all-cows-to-ducks.xsl= stylesheet will be first applied to
the incoming data (normally XML) and the
=02-convert-duck-to-escenic-xml.xsl= will be applied next before the
resulting Escenic XML will be imported into the Escenic Content
Engine.

*** Pulling content from an FTP server
We have ready made BASH libraries to do this. You only need to put a
file in =mybub/moo/cron.hourly/get-files-from-moo-ftp= like:

#+BEGIN_SRC text
#! /usr/bin/env bash
source /usr/share/escenic/engine/import/common-import-functions.sh

ftp_user="user@server.com"
ftp_password="foobar"
ftp_url=ftp://ftp.server.com/myfeed/
download_dir=/var/spool/escenic/import/mypub/moo/new
log=/var/log/escenic/cron.$(basename $0 .sh).log
ftp_download_history=/var/lib/escenic/ftp-history-cron.$(basename $0 .sh)
lock_file=/var/lock/$(basename $0 .sh).lock

now=$(date +%s)
max_file_age_in_hours=2000

echo $0 "called @ $(date)" >> $log
download_latest_ftp_files
fix_ownership_of_download_files
echo $0 "finished @ $(date)" >> $log
#+END_SRC

The only values you need to touch is are:
- =ftp_user=
- =ftp_password=
- =ftp_url= :: full URL to the directory on the FTP server.
- =download_dir= :: it's really just the =/mypub/moo= part of the
                    above example you'd  have to change.

The rest of the options should do just fine. If you really want to
tweak, you can of course decide how far back you want each run of the
import to look for files (it will only download each file once) by
setting =max_file_age_in_hours=.

This will give you many features including:
- lock file support :: only one instance of your cron FTP script will
  run at any given point in time.
- state :: only files that previously haven't been downloaded will be
           downloaded with a new run of the cron job.
- log files :: logging of your cron script in a dedEICAted file

** Import configuration deployed by VOSA

*** Setting up a new import configuration
When an EICA is gotten from a developer, the VOSA operator
will create the import configuration harness, infrastructure as with the
=ece-import= command as follows:
#+BEGIN_SRC text
$ ece-import \
  --publication-name mypub \
  --name video \
  --import-archive /tmp/my-great-import-archive.zip \
  create
#+END_SRC

The =ece-import= script will take care of putting transformers in the
right place, create spool directories and create the Nursery
configuration needed for the import job.

The =ece-import= will with the above command create an import job
with sensible defaults, the operator may override a few import
settings with these parameters:
- =--import-user= :: (the ECE user which will be the author of the
     imported contents). Default is =<publication name>=_admin
- =--import-section-name= :: the default, fallback section of imported
     content. Default is =ece_incoming=

*** Directories and Files
When an import job has been deployed by VOSA, it will use the following locations to read from and write to.

|--------------------------------------------------------------------------------------------+-------------------------------------------|
| Path                                                                                       | Description                               |
|--------------------------------------------------------------------------------------------+-------------------------------------------|
| =/var/spool/escenic/import/<pub>/<job>/new=                                                | Input folder for the 3rd party (XML) data |
| =/usr/share/escenic/engine/import/<pub>/<job>/transformers=                                | The transformers, such as XSLs            |
| =/usr/share/escenic/engine/import/mypub/moo/transformers/02-convert-all-cows-to-ducks.xsl= |                                           |
| =/var/spool/escenic/import/mypub/moo/new=                                                  |                                           |
| =/var/spool/escenic/import/<pub>/<job>/error=                                              | Failed 3rd party XML files                |
| =/var/spool/escenic/import/mypub/moo/error=                                                |                                           |
| =/var/spool/escenic/import/<pub>/<job>/archive=                                            | Successful imports of 3rd party files     |
| =/var/spool/escenic/import/mypub/moo/archive=                                              |                                           |
| =/etc/cron.hourly/<your cron script>=                                                      | Cron script running every hour            |
| =/etc/cron.hourly/get-files-from-moo-ftp=                                                  |                                           |
| =/var/log/escenic/cron.<your coron script>.log=                                            | The log for your cron script              |
| =/var/log/escenic/cron.get-files-from-moo-ftp.log=                                         |                                           |
|--------------------------------------------------------------------------------------------+-------------------------------------------|




