** Updating Publication Resources
This document describes how you update publication resources. Here, we
use content-type as an example.

The content type publication resource is special because it's merged
by WF and you thus must take it from the EAR the build server built
for you. Other publication resources could be taken directly from the
SCM, but for consistency, you can just follow the guide below for
these as well (layout, layout-group, menu, community/security and so
on).

*** Extract the publication resources.
Make sure you have already done the deployment in the pres1 server

*** Login to one of the presentation servers
#+BEGIN_SRC sh
control$ sudo ssh root@pres1  
#+END_SRC

*** Change to the escenic user
#+BEGIN_SRC sh
pres1# su - escenic
#+END_SRC

*** Download current content-type
#+BEGIN_SRC sh
pres1$ wget -O ~/backup/content-type-$(date --iso)-before-deployment \
       http://localhost:8080/escenic-admin/publication-resources/mypub/escenic/content-type
#+END_SRC

*** Locate the new content-type definition
Go to the new new content-type from your latest deployment 

#+BEGIN_SRC sh
pres1$ cd /opt/tomcat-engine1/webapps/eb/META-INF/escenic/publication-resources/escenic/
#+END_SRC

*** Confirm the changes with diff
#+BEGIN_SRC sh
pres$ diff -w ~/backup/content-type-$(date --iso)-before-deployment content-type  
#+END_SRC


*** Now upload the new content-type to ECE
The command below assumes that there is a file called the same as the
publication resource in the current directory. Since we changed into
that directory in step 5), we can therefore now do:

#+BEGIN_SRC sh
pres1$ ece -i engine1 -p mypub -r content-type update
#+END_SRC


*** Download the resource again to check if its in place
#+BEGIN_SRC sh
pres1$ wget -O ~/backup/content-type-$(date --iso)-after-deployment \
               http://localhost:8080/escenic-admin/publication-resources/mypub/escenic/content-type
#+END_SRC


*** Do check with diff again
#+BEGIN_SRC sh
pres$ diff -w ~/backup/content-type-$(date --iso)-before-deployment \
              ~/backup/content-type-$(date --iso)-after-deployment
#+END_SRC


