#! /usr/bin/env bash

rm -rf debian/{etc,usr}

target_dir=debian
package_name=escenic-content-engine-installer

function get_version()
{
    engine_file=$(grep http ../../sbin/ece-install | grep "/engine")
    version=$(basename $engine_file .zip | cut -d'-' -f2)
    echo $version
}

function get_name()
{
    name=$(grep $USER /etc/passwd | cut -d':' -f5 | cut -d',' -f1)
    echo "${name}"
}

function get_email()
{
    echo ${USER}@${HOSTNAME}
}

version=$(get_version)

cp -r ../../../etc $target_dir

mkdir -p $target_dir/usr
cp -r ../../../usr/bin $target_dir/usr
cp -r ../../../usr/sbin $target_dir/usr
cp -r ../../../usr/share $target_dir/usr

cp $target_dir/DEBIAN/control $target_dir/DEBIAN/control.orig

sed -i "s#VERSION#${version}#g" $target_dir/DEBIAN/control
sed -i "s#MAINTAINER_NAME#$(get_name)#g" $target_dir/DEBIAN/control
sed -i "s#MAINTAINER_EMAIL#$(get_email)#g" $target_dir/DEBIAN/control

# fix permissions
chmod 755 $target_dir/DEBIAN/postinst

if [ ! -x /usr/bin/dpkg-deb ]; then
    echo "You must have dpkg-deb installed :-("
    exit 1
fi

dpkg-deb --build debian
mv debian.deb ${package_name}-${version}.deb

if [[ -x /usr/bin/alien && -x /usr/bin/fakeroot ]]; then
    fakeroot alien --to-rpm --scripts ${package_name}-${version}.deb
else
    echo "You must have 'alien' and 'fakeroot' installed to create RPMs"
fi

# cleanup
cp $target_dir/DEBIAN/control.orig $target_dir/DEBIAN/control
