#! /usr/bin/env bash                                                                                            

dir=$1
log=/tmp/$(basename $0).log
apt_repo_dir=/var/www/apt

if [[ ${dir}x == "x" || ! -d $dir ]]; then
  echo "You must pass a valid directory to $(basename $0)"
  echo "For example:"
  echo "$(basename $0) /tmp/dir-with-a-lot-of-deb-files"
  exit 1
fi

echo "I'm logging to $log"

function get_package_name() {
  dpkg --info $1 | sed 's/^[ ]//'g | grep ^Package | cut -d':' -f2
}

for el in $dir/*.deb; do
  echo -n "Signing and adding $(basename $el) to the APT repository ... "
  dpkg-sig --sign builder $el >> $log 2>> $log
  reprepro -Vb $apt_repo_dir remove stable $(get_package_name $el) >> $log 2>> $log
  reprepro --ask-passphrase -Vb $apt_repo_dir includedeb stable $el >> $log 2>> $log
  echo "done"
done
